### ISSUE TITLE
using directive to change the command not working

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.az#338]
```
directive:  
    - where:
        command: datashare consumer-source-data-set list 
      set:
        command: datashare consumer-source-data-set list-modify
```
Not working
