### ISSUE TITLE
alias for non-main-resource-name it will still add -name -n into the options_list 

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.az#505]
![image](https://user-images.githubusercontent.com/55688292/90092089-9849f400-dd5a-11ea-95ce-959159971096.png)
```
      - where:
            group: ManagedPrivateEndpoints
            param: managedVirtualNetworkName
        alias:
            - managed_vnet_name
      - where:
            group: ManagedPrivateEndpoints
            param: privateLinkResourceId
        alias:
            - plr_id
```
