### ISSUE TITLE
Incompatible with existing folder structure of application-insights extension

### ISSUE THREAD

**Issue by kairu-ms** [Azure/autorest.az#592]
When extension name used in folder is different with command group, code generated cannot be compatible with existing folder structure.

## readme.az.md

``` yaml $(az)
az:
    extensions: app-insights
    namespace: azure.mgmt.applicationinsights
    package-name: azure-mgmt-applicationinsights
az-output-folder: $(azure-cli-extension-folder)/src/application-insights
python-sdk-output-folder: "$(az-output-folder)/azext_applicationinsights/vendored_sdks/applicationinsights"
# add additinal configuration here specific for Azure CLI
# refer to the faq.md for more details
cli:
    cli-directive:
        - where:
            group: "*"
          hidden: true
        - where:
            group: ExportConfigurations
          hidden: false
```

## folder structure
Before:
![image](https://user-images.githubusercontent.com/69238381/96668053-e7308d00-138c-11eb-83cc-c092012b27dc.png)

After:
![image](https://user-images.githubusercontent.com/69238381/96667955-aafd2c80-138c-11eb-9bf4-70e6059e59c0.png)
