### ISSUE TITLE
Positional Arguments test generation adaption

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.az#612]
![image](https://user-images.githubusercontent.com/55688292/97831943-784c2000-1d0c-11eb-919c-f4550ef19081.png)
As title.

To repro:
add the following cli-directive in RP billing's readme.az.md 
```
cli:
    cli-directive:
      - where:
            param: enabledAzurePlans
        set:
            positional: true
      - where:
            param: soldTo
        set:
            positional: true
            positionalKeys:
                - first_name
                - last_name
                - company_name
                - address_line1
                - country
```
