### ISSUE TITLE
test adaption for aws shorthand syntax action

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.az#627]
The aws shorthand syntax action is using , to split properties and ' ' to split between objects.
Users can use 
```
cli:
    cli-directive:
        - where:
            group: GroupName
            op: OperationName
            param: paramName
          set:
            shorthandSyntax: true
```
This kind of cli directive to use short hand syntax actions.

For example:
If sku is defined to use shorthand syntax action.
```
--sku name=XX,capacity=XX,tier=XX
```
if sku is an array. They can use ' ' to indicate that there's multiple items
```
--sku name=XX,capacity=XX,tier=XX name=XX,capacity=XX,tier=XX 
```
