### ISSUE TITLE
Cann't rename flatten parameter. Only alias supported

### ISSUE THREAD

**Issue by kairu-ms** [Azure/autorest.az#653]
azure-rest-api-specs repo [link](https://github.com/kairu-ms/azure-rest-api-specs/tree/f7dac59d684ddedc2fc3d8a7bd6f161761d5cd8a)

``` yaml
      - where:
          group: DataCollectionRules
          param: windowsEventLogs
        set:
         alias: windows_event_log
      - where:
          group: DataCollectionRules
          param: performanceCounters
        set:
         alias: performance_counter
      - where:
          group: DataCollectionRules
          param: syslog
        set:
         alias: syslog
      - where:
          group: DataCollectionRules
          param: extension
        set:
         alias: extension
      - where:
          group: DataCollectionRules
          param: destinations
        set:
          alias: destination
      - where:
          group: DataCollectionRules
          param: streams
        set:
          alias: stream

```

[Generated parameters with schema prefix 'data_source_' cannot be renamed.](https://github.com/kairu-ms/azure-cli-extensions/blob/14238a86db9c2a292385e87b68b95df119416fa9/src/monitor-control-service/azext_amcs/generated/_params.py#L74-L81)
```py
        c.argument('data_sources_performance_counters', action=AddDataSourcesPerformanceCounters, nargs='+', help='The '
                   'list of performance counter data source configurations.')
        c.argument('data_sources_windows_event_logs', action=AddDataSourcesWindowsEventLogs, nargs='+', help='The list '
                   'of Windows Event Log data source configurations.')
        c.argument('data_sources_syslog', action=AddDataSourcesSyslog, nargs='+', help='The list of Syslog data source '
                   'configurations.')
        c.argument('data_sources_extensions', type=validate_file_or_dict, help='The list of Azure VM extension data '
                   'source configurations. Expected value: json-string/@json-file.')
```
