### ISSUE TITLE
Cannot directly modify command group from 'monitor data-collection data-collection-rule-association' to 'monitor data-collection rule association'

### ISSUE THREAD

**Issue by kairu-ms** [Azure/autorest.az#654]
azure-rest-api-specs repo [link](https://github.com/kairu-ms/azure-rest-api-specs/tree/f7dac59d684ddedc2fc3d8a7bd6f161761d5cd8a)

Cannot directly modify command group from 
```
monitor data-collection data-collection-rule-association
```
 to 
```
monitor data-collection rule association
```

Currently we have to add two rules to achieve that.
Part of [readme.az.md](https://github.com/kairu-ms/azure-rest-api-specs/blob/f7dac59d684ddedc2fc3d8a7bd6f161761d5cd8a/specification/monitor/resource-manager/readme.az.md)

``` yaml
  - where:
      group: monitor data-collection data-collection-rule-association
    set:
      group: monitor data-collection rule-association
  - where:
      group: monitor data-collection rule-association
    set:
      group: monitor data-collection rule association
```
