### ISSUE TITLE
Operations_list is inconsistent by alias configuration. Why '--data-collection-rule-name' added?

### ISSUE THREAD

**Issue by kairu-ms** [Azure/autorest.az#655]
part of [readme.az.md](https://github.com/kairu-ms/azure-rest-api-specs/blob/1ca77f8d34c0e2d2d8a56fb8b5f35fffbd6d5d70/specification/monitor/resource-manager/readme.az.md)

```yaml
      - where:
          group: DataCollectionRules
          param: dataCollectionRuleName
        alias:
          - name
          - n
      - where:
          group: DataCollectionRuleAssociations
          param: dataCollectionRuleName
        alias:
          - rule_name
      - where:
          group: DataCollectionRuleAssociations
          param: associationName
        alias:
          - name
          - n
```

[Generated 'data_collection_rule_name' paramter in 'monitor data-collection rule association list'](https://github.com/kairu-ms/azure-cli-extensions/blob/0ccfb1a2619ab65344886469730d27581683c7b6/src/monitor-control-service/azext_amcs/generated/_params.py#L20-L21)

```py
    with self.argument_context('monitor data-collection rule association list') as c:
        c.argument('resource_group_name', resource_group_name_type)
        c.argument('data_collection_rule_name', options_list=['--rule-name'], type=str, help='The name of the data '
                   'collection rule. The name is case insensitive.')
        c.argument('resource_uri', options_list=['--resource'], type=str, help='The identifier of the resource.')
```

[Generated 'data_collection_rule_name' paramter in 'monitor data-collection rule show'](https://github.com/kairu-ms/azure-cli-extensions/blob/0ccfb1a2619ab65344886469730d27581683c7b6/src/monitor-control-service/azext_amcs/generated/_params.py#L37-L38)

```py
    with self.argument_context('monitor data-collection rule show') as c:
        c.argument('resource_group_name', resource_group_name_type)
        c.argument('data_collection_rule_name', options_list=['--name', '-n', '--data-collection-rule-name'], type=str,
                   help='The name of the data collection rule. The name is case insensitive.', id_part='name')
```
[Generated 'association_name' paramter in 'monitor data-collection rule association delete'](https://github.com/kairu-ms/azure-cli-extensions/blob/0ccfb1a2619ab65344886469730d27581683c7b6/src/monitor-control-service/azext_amcs/generated/_params.py#L30)

```py
    with self.argument_context('monitor data-collection rule association delete') as c:
        c.argument('resource_uri', options_list=['--resource'], type=str, help='The identifier of the resource.')
        c.argument('association_name', options_list=['--name', '-n'], type=str, help='The name of the association.')
```
