### ISSUE TITLE
Command Rename bug 

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.az#710]
```
directive:
  - where:
        group: offazure hyper-v-cluster
    set:
        group: offazure hyperv cluster
  - where:
        command: offazure hyperv cluster show-all-cluster-in-site
    set:
        command: offazure hyperv cluster list
  - where:
        command: offazure hyperv cluster show-cluster
    set:
        command: offazure hyperv cluster show
```

The result is 

```
    from azext_offazure.generated._client_factory import cf_hyper_vcluster
    offazure_hyper_vcluster = CliCommandType(
        operations_tmpl='azext_offazure.vendored_sdks.offazure.operations._hyper_vcluster_operations#HyperVClusterOpera'
        'tions.{}',
        client_factory=cf_hyper_vcluster)
    with self.command_group('offazure hyperv cluster', offazure_hyper_vcluster,
                            client_factory=cf_hyper_vcluster) as g:
        g.custom_command('cluster list', 'offazure_hyperv_cluster_list')
        g.custom_show_command('cluster show', 'offazure_hyperv_cluster_show')
```
