### ISSUE TITLE
depth coverage: wrong _client_factory path in commands.py in core mode

### ISSUE THREAD

**Issue by changlong-liu** [Azure/autorest.az#722]
The "azext_network" in import path don't exist
![image](https://user-images.githubusercontent.com/59815250/106086112-74d60280-615c-11eb-8b46-3c0d8f32cf2b.png)

generate command:
autorest --version=3.0.6271 --az --use=. c:\zz\projects\codegen\azure-rest-api-specs\specification\network\resource-manager\readme.md --azure-cli-folder=..\azure-cli   --target-mode=core  --compatible-level=track2 --generate-sdk=yes

az.md:

``` yaml $(az)
az:
  extensions: network
  namespace: azure.mgmt.network
  package-name: azure-mgmt-network
  disable-checks: true
  randomize-names: true
  test-unique-resource: true
az-output-folder: $(azure-cli-folder)/src/azure-cli/azure/cli/command_modules/network
python-sdk-output-folder: "$(azure-cli-folder)/src/azure-cli/azure/cli/command_modules/network/vendored_sdks/network"
compatible-level: track2
```
