### ISSUE TITLE
[Bug] Wrong experimental label in generated code

### ISSUE THREAD

**Issue by qwordy** [Azure/autorest.az#738]
When I generated `ssh`, I got
```
    with self.command_group('vm', is_experimental=True):
        pass
```
`vm` is mature. Can we remove `experimental`?

`readme.az.md`:

``` yaml $(az) && $(target-mode) == "core"
az:
  extensions: vm
  namespace: azure.mgmt.compute
  package-name: azure-mgmt-compute
az-output-folder: $(azure-cli-folder)/src/azure-cli/azure/cli/command_modules/vm
python-sdk-output-folder: "$(az-output-folder)/vendored_sdks/vm"
cli:
    cli-directive:
        - where:
            group: "*"
            op: "*"
          hidden: true
        - where:
            group: "SshPublicKeys"
            op: "*"
          hidden: false
directive: 
  - where: 
      command: vm ssh-public-key
    set:
      command: sshkey
```
