### ISSUE TITLE
Rename group/command/parameter in one step

### ISSUE THREAD

**Issue by jsntcy** [Azure/autorest.az#779]
Currently if you want to rename group: `network express-route-circuit-connection` to group: `network express-route peering connection`, you need set configuration as follows in readme.az.md
```
- where:
      group: network express-route-circuit-connection
    set:
      group: network express-route-peering-connection
  - where:
      group: network express-route-peering-connection
    set:
      group: network express-route peering-connection
  - where:
      group: network express-route peering-connection
    set:
      group: network express-route peering connection
```
can we just config as follows to achieve the goal to make the config easier for us?
```
- where:
      group: network express-route-circuit-connection
    set:
      group: network express-route peering connection
```
