### ISSUE TITLE
Cannot config `completer` and `validator` property of argument.

### ISSUE THREAD

**Issue by kairu-ms** [Azure/autorest.az#789]
Current
```python
c.argument('circuit_name', type=str, help='The name of the circuit.')
```
Prefer
```python
c.argument('circuit_name', type=str, help='The name of the circuit.', completer=get_resource_name_completion_list('Microsoft.Network/expressRouteCircuits'))
```

**Comment by qiaozha** [comment]
Plan to support in the following way: 
cli:
    cli-directive:
        - where:
               group: groupName
           feature:
                completer: completer_name
                validator: validator_name

**Comment by kairu-ms** [comment]
> Plan to support in the following way:
> cli:
> cli-directive:
> - where:
> group: groupName
> feature:
> completer: completer_name
> validator: validator_name

How can you find completer function only by it's name? Do you need import path?

**Comment by qiaozha** [comment]
> > Plan to support in the following way:
> > cli:
> > cli-directive:
> > 
> > * where:
> >   group: groupName
> >   feature:
> >   completer: completer_name
> >   validator: validator_name
> 
> How can you find completer function only by it's name? Do you need import path?

```
cli:
  cli-directive:
  - where:
        group: groupName
     feature:
        completer: completer_name
        validator: validator_name
        imports:
            - azure.cli.core.completer.MyCompleter
            - azure.cli.core.validator.MyValidator
```

how about something like this?
