### ISSUE TITLE
"CreateOrUpdate#Update" could not be generated

### ISSUE THREAD

**Issue by xfz11** [Azure/autorest.az#834]
**Why do you need this feature?**
Generate update command by 'CreateOrUpdate' API

**Is your feature request related to a problem? Please describe.**

In [readme.az.md](https://github.com/Azure/azure-rest-api-specs/blob/8b70a8bafb1162685df3ca58b042675a47306f60/specification/compute/resource-manager/readme.az.md)
I set 
```
- where:
      group: "Galleries"
      op: "CreateOrUpdate#Update"
    hidden: false
```
However, the `update `command is not generated.
 

**The following code snippet is a generated help message.**

**Describe the solution you'd like**
Generate the code as the readme declarer

**Describe alternatives you've considered**

**Additional context**
