### ISSUE TITLE
Alias for discriminator options not working

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.az#837]
`--factory-git-hub-configuration` and `--factory-vsts-configuration` are discriminator options for the`repoConfiguration` property in the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/f1d8c4ebb54fdc1301eb2f2a465982cf58b54f69/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json#L5025-L5028) to create a data factory.
The violate the `option_length_too_long` linter rule. I tried to add alias for them, but the below configuration does not work.
```
    - where:
          group: Factories
          type: FactoryGitHubConfiguration
      alias:
          - factory-git-hub-configuration
          - github-config
    - where:
          group: Factories
          type: FactoryVSTSConfiguration
      alias:
          - factory-vsts-configuration
          - vsts-config
```
