### ISSUE TITLE
Polling is set to False in generated vendored sdk so long running operations do not work

### ISSUE THREAD

**Issue by hivyas** [Azure/autorest.az#883]
When generating an Azure cli extension the vendor sdk makes polling=False so that even when sdk_no_wait is False, long running operations don't complete. 

This is the readme.az.md I am using to generate:

```
az:
    extensions: videoanalyzer
    namespace: azure.mgmt.videoanalyzer
    package-name: azure-mgmt-videoanalyzer
az-output-folder: $(azure-cli-extension-folder)/src/videoanalyzer
python-sdk-output-folder: "$(az-output-folder)/azext_videoanalyzer/vendored_sdks/videoanalyzer"
```

And the rest api specs can be found [here](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/videoanalyzer/resource-manager/Microsoft.Media/preview/2021-11-01-preview)
